export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  MANAGEMENT = 'ROLE_MANAGEMENT',
  CONTROL_ROOM_MANAGER = 'ROLE_CONTROL_ROOM_MANAGER',
  DISPATCHER = 'ROLE_DISPATCHER',
  LOGGIST = 'ROLE_LOGGIST',
  CLINICIAN = 'ROLE_CLINICIAN',
}
