export enum Perms {
  CREATE_EVENT = 'CREATE_EVENT',

  CREATE_CALL = 'CREATE_CALL',

  CLOSE_CALL = 'CLOSE_CALL',

  MANAGE_CALL_RESOURCE = 'MANAGE_CALL_RESOURCE',

  MANAGE_RESOURCES = 'MANAGE_RESOURCES',

  ADDLOG = 'ADDLOG',

  MANAGE_BREAKS = 'MANAGE_BREAKS',

  ADMIN = 'ADMIN',
}
