export enum ResourceType {
  AMBULANCE = 'AMBULANCE',

  CYCLERESPONSE = 'CYCLERESPONSE',

  FOOTTEAM = 'FOOTTEAM',

  LOGISTICS = 'LOGISTICS',

  MANAGEMENT = 'MANAGEMENT',

  TREATMENTCENTRE = 'TREATMENTCENTRE',
}
